# -*- coding: utf-8 -*-
"""Tomelinks_Classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GTN2Q9XyFLIyex-nmuU7PB8k4tUmSW-q
"""
import random
import sys
import numpy as np # linear algebra
#np.set_printoptions(threshold=sys.maxsize)
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import re
import csv
import time
from scipy import stats
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from timeit import default_timer as timer

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

import os
# print(os.listdir("../input"))
plt.style.use('ggplot')

df = pd.DataFrame()

raw = open(r"C:\\Users\\z3696\\Documents\\Document-Classification\\classifier\\NIST_FULL\\2010-neg.txt", encoding="ISO-8859-1")
lines = raw.readlines()
raw.close()

# remove /n at the end of each line
for index, line in enumerate(lines):
    lines[index] = line.strip()
    print(lines[index])

neg_df = pd.DataFrame(columns=['sentence'])
i = 0
first_col = ""
for line in lines:
    first_col = re.sub(r' \(.*', "", line)
    neg_df.loc[i] = [first_col]
    i = i+1

neg_df.head()
neg_df['label'] = 0
print(neg_df.shape)

raw1 = open(r"C:\\Users\\z3696\\Documents\\Document-Classification\\classifier\\NIST_FULL\\2010-pos.txt", encoding="ISO-8859-1")
lines1 = raw1.readlines()
raw1.close()

# remove /n at the end of each line
for index, line in enumerate(lines1):
    lines1[index] = line.strip()
    print(lines1[index])

pos_df = pd.DataFrame(columns=['sentence'])
i = 0
first_col = ""
for line in lines1:
    first_col = re.sub(r' \(.*', "", line)
    pos_df.loc[i] = [first_col]
    i = i+1

pos_df.head()
pos_df['label'] = 1

df = df.append(pos_df)
df = df.append(neg_df)
print(df)
print(pos_df.shape)
print(neg_df.shape)

import pandas as pd
import numpy as np
import nltk
import re
import string
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support as score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem.wordnet import WordNetLemmatizer
import string
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tag import pos_tag
from nltk.tokenize import word_tokenize
nltk.download('wordnet')
nltk.download('stopwords')
stopwords.words('english')

#Removing punctuations from entire dataset
punc_set = string.punctuation
punc_set

#Function for removing punctions
def remove_punc(text):
    clean = "".join([x.lower() for x in text if x not in punc_set])
    return clean

#Applying the 'remove_punc' function to entire dataset
df['no_punc'] = df['sentence'].apply(lambda z:remove_punc(z))

#Function for Tokenizing entire data for representing every word as datapoint
def tokenize(text):
    tokens = re.split("\W+",text)
    return tokens

#Applying the 'tokenize' function to entire dataset
df['tokenized_Data'] = df['no_punc'].apply(lambda z:tokenize(z))

#Importing stopwords from NLTK Library to remove stopwords now that we have tokenized it
stopwords = nltk.corpus.stopwords.words('english')

#Function for removing stopwords from single row
def remove_stopwords(tokenized_words):
    Ligit_text=[word for word in tokenized_words if word not in stopwords]
    return Ligit_text

#Applying the function 'remove_stopwords' from the entire dataset
df["no_stop"] = df["tokenized_Data"].apply(lambda z:remove_stopwords(z))

#Importing 'WordNetLemmatizer' as lemmatizing function to find lemma's of words
wnl = nltk.wordnet.WordNetLemmatizer()

#Function for lemmatizing the tokenzied text
def lemmatizing(tokenized_text):
    lemma = [wnl.lemmatize(word) for word in tokenized_text]
    return lemma

#Applying the 'lemmatizing' function to entire dataset
df['lemmatized'] = df['no_stop'].apply(lambda z:lemmatizing(z))

# #Importing the 'SnowballStemmer' and declaring variable 'sno' to save the stemmer in.
# #This Stemmer gives slightly better results as compared to 'PorterStemmer'
# sno = nltk.SnowballStemmer('english')

# #Function for applying stemming to find stem roots of all words
# def stemming(tokenized_text):
#     text= [sno.stem(word) for word in tokenized_text]
#     return text

# #Applying the 'stemming' function to entire dataset
# data['ss_stemmed'] = data['lemmatized'].apply(lambda z:stemming(z))


# ps = nltk.PorterStemmer()

# def stemming(tokenized_text):
#     text= [ps.stem(word) for word in tokenized_text]
#     return text

# data['ps_stemmed'] = data['lemmatized'].apply(lambda z:stemming(z))

#This step is done here because, the 'lemmatized' column is a list of tokenized words and when we apply vectorization
#techniques such as count vectorizer or TFIDF, they require string input. Hence convert all tokenzied words to string
df['lemmatized'] = [" ".join(review) for review in df['lemmatized'].values]

df.head()

time.sleep(500)

pos_num = 29708

pos_95 = round(pos_num * 0.95)
pos_85 = round(pos_num * 0.85)
pos_75 = round(pos_num * 0.75)
pos_65 = round(pos_num * 0.65)
pos_55 = round(pos_num * 0.55)
pos_45 = round(pos_num * 0.45)
pos_35 = round(pos_num * 0.35)
pos_25 = round(pos_num * 0.25)
pos_15 = round(pos_num * 0.15)
pos_05 = round(pos_num * 0.05)

neg_num = 48521

neg_95 = round(neg_num * 0.95)
neg_85 = round(neg_num * 0.85)
neg_75 = round(neg_num * 0.75)
neg_65 = round(neg_num * 0.65)
neg_55 = round(neg_num * 0.55)
neg_45 = round(neg_num * 0.45)
neg_35 = round(neg_num * 0.35)
neg_25 = round(neg_num * 0.25)
neg_15 = round(neg_num * 0.15)
neg_05 = round(neg_num * 0.05)

# Splitting Datasets Manually
pos_pt1=df.iloc[0:pos_num-pos_95 :]
neg_pt1=df.iloc[neg_num:neg_num+neg_95, :]
pos_pt2=df.iloc[0:pos_num-pos_85, :]
neg_pt2=df.iloc[neg_num:neg_num+neg_85, :]
pos_pt3=df.iloc[0:pos_num-pos_75, :]
neg_pt3=df.iloc[neg_num:neg_num+neg_75, :]
pos_pt4=df.iloc[0:pos_num-pos_65, :]
neg_pt4=df.iloc[neg_num:neg_num+neg_65, :]
neg_pt5=df.iloc[0:pos_num-pos_55, :]
pos_pt5=df.iloc[neg_num:neg_num+neg_55, :]
pos_pt6=df.iloc[0:pos_num-pos_45, :]
neg_pt6=df.iloc[neg_num:neg_num+neg_45, :]
pos_pt7=df.iloc[0:pos_num-pos_35, :]
neg_pt7=df.iloc[neg_num:neg_num+neg_35, :]
pos_pt8=df.iloc[0:pos_num-pos_25, :]
neg_pt8=df.iloc[neg_num:neg_num+neg_25, :]
pos_pt9=df.iloc[0:pos_num-pos_15, :]
neg_pt9=df.iloc[neg_num:neg_num+neg_15, :]
neg_pt10=df.iloc[0:pos_num-pos_05, :]
pos_pt10=df.iloc[neg_num:neg_num+neg_05, :]
'''
# Splitting Datasets Manually
pos_pt1=df.iloc[0:pos_num-xy_num10, :]
neg_pt1=df.iloc[neg_num:neg_num+xy_num1, :]
pos_pt2=df.iloc[0:pos_num-xy_num9, :]
neg_pt2=df.iloc[neg_num:neg_num+xy_num2, :]
pos_pt3=df.iloc[0:pos_num-xy_num8, :]
neg_pt3=df.iloc[neg_num:neg_num+xy_num3, :]
pos_pt4=df.iloc[0:pos_num-xy_num7, :]
neg_pt4=df.iloc[neg_num:neg_num+xy_num4, :]
neg_pt5=df.iloc[0:pos_num-xy_num6, :]
pos_pt5=df.iloc[neg_num:neg_num+xy_num5, :]
pos_pt6=df.iloc[0:pos_num-xy_num5, :]
neg_pt6=df.iloc[neg_num:neg_num+xy_num6, :]
pos_pt7=df.iloc[0:pos_num-xy_num4, :]
neg_pt7=df.iloc[neg_num:neg_num+xy_num7, :]
pos_pt8=df.iloc[0:pos_num-xy_num3, :]
neg_pt8=df.iloc[neg_num:neg_num+xy_num8, :]
pos_pt9=df.iloc[0:pos_num-xy_num2, :]
neg_pt9=df.iloc[neg_num:neg_num+xy_num9, :]
neg_pt10=df.iloc[0:pos_num-xy_num1, :]
pos_pt10=df.iloc[neg_num:neg_num+xy_num10, :]
'''
df1 = pd.concat([pos_pt1, neg_pt1])
print("DF1:", round(df1.shape[0]))
df2 = pd.concat([pos_pt2, neg_pt2])
print("DF2:", round(df2.shape[0]))
df3 = pd.concat([pos_pt3, neg_pt3])
print("DF3:", round(df3.shape[0]))
df4 = pd.concat([pos_pt4, neg_pt4])
print("DF4:", round(df4.shape[0]))
df5 = pd.concat([pos_pt5, neg_pt5])
print("DF5:", round(df5.shape[0]))
df6 = pd.concat([pos_pt6, neg_pt6])
print("DF6:", round(df6.shape[0]))
df7 = pd.concat([pos_pt7, neg_pt7])
print("DF7:", round(df7.shape[0]))
df8 = pd.concat([pos_pt8, neg_pt8])
print("DF8:", round(df8.shape[0]))
df9 = pd.concat([pos_pt9, neg_pt9])
print("DF9:", round(df9.shape[0]))
df10 = pd.concat([pos_pt10, neg_pt10])
print("DF10:", round(df10.shape[0]))
#Splitting data into smaller dataframes for the purpose of Training and Testing

df1_l = "Split 1"
df2_l = "Split 2"
df3_l = "Split 3"
df4_l = "Split 4"
df5_l = "Split 5"
df6_1 = "Split 6"
df7_l = "Split 7"
df8_l = "Split 8"
df9_l = "Split 9"
df10_l = "Split 10"

ts01 = "TS 0.1"
ts02 = "TS 0.2"
ts03 = "TS 0.3"
ts04 = "TS 0.4"
ts05 = "TS 0.5"

df1_split = round(df1.shape[0] * .5)
print(df1_split)
df2_split = round(df2.shape[0] * .5)
print(df2_split)
df3_split = round(df3.shape[0] * .5)
print(df3_split)
df4_split = round(df4.shape[0] * .5)
print(df4_split)
df5_split = round(df5.shape[0] * .5)
print(df5_split)
df6_split = round(df6.shape[0] * .5)
print(df6_split)
df7_split = round(df7.shape[0] * .5)
print(df7_split)
df8_split = round(df8.shape[0] * .5)
print(df8_split)
df9_split = round(df9.shape[0] * .5)
print(df9_split)
df10_split = round(df10.shape[0] * .5)
print(df10_split)

'''
xy_ran1=random.randint(1, df.shape[0])
xy_ran2=random.randint(1, df.shape[0])
xy_ran3=random.randint(1, df.shape[0])
xy_ran4=random.randint(1, df.shape[0])
xy_ran5=random.randint(1, df.shape[0])
xy_ran6=random.randint(1, df.shape[0])
xy_ran7=random.randint(1, df.shape[0])
xy_ran8=random.randint(1, df.shape[0])
xy_ran9=random.randint(1, df.shape[0])
xy_ran10=random.randint(1, df.shape[0])
'''

df1_sen = round(df1.shape[0])
df2_sen = round(df2.shape[0])
df3_sen = round(df3.shape[0])
df4_sen = round(df4.shape[0])
df5_sen = round(df5.shape[0])
df6_sen = round(df6.shape[0])
df7_sen = round(df7.shape[0])
df8_sen = round(df8.shape[0])
df9_sen = round(df9.shape[0])
df10_sen = round(df10.shape[0])

x1 = df1.iloc[0:df1_split,5]
x2 = df1.iloc[df1_sen-df1_split:df1_sen,5]
x3 = df2.iloc[0:df2_split,5]
x4 = df2.iloc[df2_sen-df2_split:df2_sen,5]
x5 = df3.iloc[0:df3_split,5]
x6 = df3.iloc[df3_sen-df3_split:df3_sen,5]
x7 = df4.iloc[0:df4_split,5]
x8 = df4.iloc[df4_sen-df4_split:df4_sen,5]
x9 = df5.iloc[0:df5_split,5]
x10 = df5.iloc[df5_sen-df5_split:df5_sen,5]
x11 = df6.iloc[0:df6_split,5]
x12 = df6.iloc[df6_sen-df6_split:df6_sen,5]
x13 = df7.iloc[0:df7_split,5]
x14 = df7.iloc[df7_sen-df7_split:df7_sen,5]
x15 = df8.iloc[0:df8_split,5]
x16 = df8.iloc[df8_sen-df8_split:df8_sen,5]
x17 = df9.iloc[0:df9_split,5]
x18 = df9.iloc[df9_sen-df9_split:df9_sen,5]
x19 = df10.iloc[0:df10_split,5]
x20 = df10.iloc[df10_sen-df10_split:df10_sen,5]

y1 = df1.iloc[0:df1_split,1]
y2 = df1.iloc[df1_sen-df1_split:df1_sen,1]
y3 = df2.iloc[0:df2_split,1]
y4 = df2.iloc[df2_sen-df2_split:df2_sen,1]
y5 = df3.iloc[0:df3_split,1]
y6 = df3.iloc[df3_sen-df3_split:df3_sen,1]
y7 = df4.iloc[0:df4_split,1]
y8 = df4.iloc[df4_sen-df4_split:df4_sen,1]
y9 = df1.iloc[0:df1_split,1]
y10 = df1.iloc[df1_sen-df1_split:df1_sen,1]
y11 = df6.iloc[0:df6_split,1]
y12 = df6.iloc[df6_sen-df6_split:df6_sen,1]
y13 = df7.iloc[0:df7_split,1]
y14 = df7.iloc[df7_sen-df7_split:df7_sen,1]
y11 = df8.iloc[0:df8_split,1]
y16 = df8.iloc[df8_sen-df8_split:df8_sen,1]
y17 = df9.iloc[0:df9_split,1]
y18 = df9.iloc[df9_sen-df9_split:df9_sen,1]
y19 = df10.iloc[0:df10_split,1]
y20 = df10.iloc[df10_sen-df10_split:df10_sen,1]



#x_seg = df.iloc[0:5,5]
#y_seg = df.iloc[0:5,1]
print("X1:", x1.shape)
print("X2:", x2.shape)
print("X3:", x3.shape)
print("X4:", x4.shape)
print("X5:", x5.shape)
print("X6:", x6.shape)
print("X7:", x7.shape)
print("X8:", x8.shape)
print("X9:", x9.shape)
print("X10:", x10.shape)
print("Y1:", y1.shape)
print("Y2:", y2.shape)
print("Y3:", y3.shape)
print("Y4:", y4.shape)
print("Y5:", y5.shape)
print("Y6:", y6.shape)
print("Y7:", y7.shape)
print("Y8:", y8.shape)
print("Y9:", y9.shape)
print("Y10:", y10.shape)

'''
x = df['lemmatized'].values
y = df['label'].values
print(x.shape)
print(y.shape)
'''
'''
train_set = [x1,x3,x5,x7,x9]
test_set = [x2,x4,x6,x8,x10]

train_label = [y1,y3,y5,y7,y9]
test_set = [y2,y4,y6,y8,y10]
'''
#Declaring and applying TFIDF functions to train and test data

tfidf_vect = TfidfVectorizer(ngram_range=(1,2))
tfidf_train = tfidf_vect.fit_transform(x1.values)
tfidf_test=tfidf_vect.transform(x2.values)
print(tfidf_train.shape)
print(tfidf_test.shape)
#tfidf_train.toarray()

#from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
'''
# Values for testing set - PTest
Accuracy_LRN = []
Precision_LRN = []
Recall_LRN = []

Accuracy_DCT = []
Recall_DCT = []
Precision_DCT = []

Accuracy_NBB = []
Recall_NBB = []
Precision_NBB = []

Accuracy_XGB = []
Recall_XGB = []
Precision_XGB = []

# Values for testing set - Sampling
Accuracy_LRN_s = []
Precision_LRN_s = []
Recall_LRN_s = []

Accuracy_DCT_s = []
Recall_DCT_s = []
Precision_DCT_s = []

Accuracy_NBB_s = []
Recall_NBB_s = []
Precision_NBB_s = []

Accuracy_XGB_s = []
Recall_XGB_s = []
Precision_XGB_s = []
'''
'''
# Values for training set - PTest
Accuracy_LRN_tr = []
Precision_LRN_tr = []
Recall_LRN_tr = []

Accuracy_DCT_tr = []
Recall_DCT_tr = []
Precision_DCT_tr = []

Accuracy_NBB_tr = []
Recall_NBB_tr = []
precision_NBB_tr = []

Accuracy_RDD_tr = []
Recall_RDD_tr = []
precision_RDD_tr = []
'''
tfidf_vect = TfidfVectorizer()

#== DF1 ==
x_tfidf = tfidf_vect.fit_transform(df["lemmatized"])


df['label'].value_counts()

import seaborn as sns
g = sns.countplot(df1['label'])
g.set_xticklabels(['Negative','Positive'])
plt.show()

# class count
label_count_neg, label_count_pos = df['label'].value_counts()

# Separate class
label_neg = df1[df1['label'] == 0]
label_pos = df1[df1['label'] == 1]# print the shape of the class
print('Label Negative:', label_neg.shape)
print('Label Positive:', label_pos.shape)

label_neg_under = label_neg.sample(label_count_pos)

test_under = pd.concat([label_neg_under, label_pos], axis=0)

print("total class of pos and neg :",test_under['label'].value_counts())# plot the count after under-sampling
test_under['label'].value_counts().plot(kind='bar', title='label (target)')

label_pos_over = label_pos.sample(label_count_neg, replace=True)

test_over = pd.concat([label_pos_over, label_neg], axis=0)

print("total class of pos and neg:",test_under['label'].value_counts())# plot the count after under-sampeling
test_over['label'].value_counts().plot(kind='bar', title='label (target)')

import imblearn

# import library
from collections import Counter
from imblearn.under_sampling import RandomUnderSampler
x = x_tfidf
y = df['label']
print(x.shape)
print(y.shape)


rus = RandomUnderSampler(random_state=42, replacement=True)# fit predictor and target variable
x_rus, y_rus = rus.fit_resample(x, y)

print('Original dataset shape:', Counter(y))
print('Resample dataset shape', Counter(y_rus))

# import library
from collections import Counter
from imblearn.over_sampling import RandomOverSampler
'''
x =x_tfidf
y = df1["label"]
'''
ros = RandomUnderSampler(random_state=42)
#ros = RandomOverSampler(random_state=42)
#Random over-sampling with imblearn
# fit predictor and target variable
x_rus, y_rus = rus.fit_resample(x, y)

print('Original dataset shape', Counter(y))
print('Resample dataset shape', Counter(y_rus))
#Random over-sampling with imblearn
ros = RandomOverSampler(random_state=42)

# fit predictor and target variable
x_ros, y_ros = ros.fit_resample(x, y)

print('Original dataset shape', Counter(y))
print('Resample dataset shape', Counter(y_ros))
# import library

# Under-sampling: Tomek links
from imblearn.under_sampling import TomekLinks
from collections import Counter


tl = RandomOverSampler(sampling_strategy='majority')

# fit predictor and target variable
x_tl, y_tl = ros.fit_resample(x, y)

print('Original dataset shape', Counter(y))
print('Resample dataset shape', Counter(y_ros))

# import library
from imblearn.over_sampling import SMOTE

smote = SMOTE()

# fit predictor and target variable
x_smote, y_smote = smote.fit_resample(x, y)

print('Original dataset shape', Counter(y))
print('Resample dataset shape', Counter(y_ros))


from imblearn.under_sampling import NearMiss

nm = NearMiss()

x_nm, y_nm = nm.fit_resample(x, y)

print('Original dataset shape:', Counter(y))
print('Resample dataset shape:', Counter(y_nm))

probs_lr_scol = []
f1_lr_scol = []
rocauc_lr_scol = []
recall_lr_scol = []
precision_lr_scol = []
accuracy_lr_scol = []

probs_dt_scol = []
f1_dt_scol = []
rocauc_dt_scol = []
recall_dt_scol = []
precision_dt_scol = []
accuracy_dt_scol = []

probs_nb_scol = []
f1_nb_scol = []
rocauc_nb_scol = []
recall_nb_scol = []
precision_nb_scol = []
accuracy_nb_scol = []

probs_xg_scol = []
f1_xg_scol = []
rocauc_xg_scol = []
recall_xg_scol = []
precision_xg_scol = []
accuracy_xg_scol = []

probs_rf_scol = []
f1_rf_scol = []
rocauc_rf_scol = []
recall_rf_scol = []
precision_rf_scol = []
accuracy_rf_scol = []


train_values= np.array([0.037, 0.090, 0.146])
# 0.219, 0.229, 0.300, 0.335, 0.380, 0.415, 0.465
test_sizes = np.array([0.5, 0.6, 0.7])
#train_sizes = round(train_list, 3)
for i in train_values:
    # train_sizes = train_sizes + i
    #random_portion = round(np.random.uniform(0.2, 0.5), 3)
    #print(random_portion)
    x_train, x_test, y_train, y_test = train_test_split(x_tl,y_tl, train_size=i, test_size=test_sizes[0])

    start1 = time.time()
    log = LogisticRegression(penalty='l2',random_state=0, solver='lbfgs', multi_class='auto', max_iter=500)
    model_lr = log.fit(x_train,y_train)
    probs_lr = model_lr.predict_proba(x_test)[:, 1]
    probs_lr_scol.append(probs_lr)
    ly_prediction = log.predict(x_test)
    fly = f1_score(ly_prediction,y_test)
    f1_lr_scol.append(fly)
    rocauc_lr = roc_auc_score(y_test, ly_prediction)
    rocauc_lr_scol.append(rocauc_lr)
    recalls_lr = recall_score(y_test, ly_prediction)
    recall_lr_scol.append(recalls_lr)
    precisions_lr = precision_score(y_test, ly_prediction)
    precision_lr_scol.append(precisions_lr)
    accuracys_lr = accuracy_score(y_test, ly_prediction)
    accuracy_lr_scol.append(accuracys_lr)
    print("===Logistic Regression with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[0], i)
    lr_end = time.time()
    print('Logistic F1-score',fly*100)
    print('Logistic ROCAUC score:',rocauc_lr*100)
    print('Logistic Recall score:', recalls_lr*100)
    print('Logistic Precision Score:', precisions_lr*100)
    print('Logistic Confusion Matrix', confusion_matrix(y_test,ly_prediction), "\n")
    print('Logistic Classification', classification_report(y_test,ly_prediction), "\n")
    print('Logistic Accuracy Score', accuracys_lr*100)
    print("Execution Time for Logistic Regression Tomelinks: ", lr_end - start1, "seconds")

    start2 = time.time()
    from sklearn.tree import DecisionTreeClassifier
    DCT = DecisionTreeClassifier()
    model_dt = DCT.fit(x_train, y_train)
    probs_dt = model_dt.predict_proba(x_test)[:, 1]
    probs_dt_scol.append(probs_dt)
    dct_pred = DCT.predict(x_test)
    fdct = f1_score(dct_pred,y_test)
    f1_dt_scol.append(fdct)
    rocauc_dt = roc_auc_score(y_test, dct_pred)
    rocauc_dt_scol.append(rocauc_dt)
    recalls_dt = recall_score(y_test, dct_pred)
    recall_dt_scol.append(recalls_dt)
    precisions_dt = precision_score(y_test, dct_pred)
    precision_dt_scol.append(precisions_dt)
    accuracys_dt = accuracy_score(y_test, dct_pred)
    accuracy_dt_scol.append(accuracys_dt)
    print("===DecisionTreeClassifier with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[0], i)
    dt_end = time.time()
    print('DCT F1-score',fdct*100)
    print('DCT ROCAUC score:',rocauc_dt*100)
    print('DCT Recall score:', recalls_dt*100)
    print('DCT Precision Score:', precisions_dt*100)
    print('DCT Confusion Matrix', confusion_matrix(y_test, dct_pred), "\n")
    print('DCT Classification', classification_report(y_test, dct_pred), "\n")
    print('DCT Accuracy Score', accuracys_dt*100)
    print("Execution Time for Decision Tree Tomelinks: ", dt_end - start2, "seconds")


    from sklearn.naive_bayes import MultinomialNB
    start3 = time.time()
    Naive = MultinomialNB()
    model_nb = Naive.fit(x_train,y_train)
    probs_nb = model_nb.predict_proba(x_test)[:, 1]
    probs_nb_scol.append(probs_nb)
    # predict the labels on validation dataset
    ny_pred = Naive.predict(x_test)
    fnb = f1_score(ny_pred,y_test)
    f1_nb_scol.append(fnb)
    rocauc_nb = roc_auc_score(y_test, ny_pred)
    rocauc_nb_scol.append(rocauc_nb)
    recalls_nb = recall_score(y_test, ny_pred)
    recall_nb_scol.append(recalls_nb)
    precisions_nb = precision_score(y_test, ny_pred)
    precision_nb_scol.append(precisions_nb)
    accuracys_nb = accuracy_score(y_test, ny_pred)
    accuracy_nb_scol.append(accuracys_nb)
    nb_end = time.time()
    # Use accuracy_score function to get the accuracy
    print("===Naive Bayes with TfidfVectorizer Imabalanced - 2010", df1_l, test_sizes[0], i)
    print('Naive F1-score',fnb*100)
    print('Naive ROCAUC score:',rocauc_nb*100)
    print('Naive Recall score:', recalls_nb*100)
    print('Naive Precision Score:', precisions_nb*100)
    print('Naive Confusion Matrix', confusion_matrix(y_test, ny_pred), "\n")
    print('Naive Classification', classification_report(y_test, ny_pred), "\n")
    print('Naive Accuracy Score', accuracys_nb*100)
    print("Execution Time for Naive Bayes Tomelinks: ", nb_end - start3, "seconds")

# XGBoost Classifier

    start4 = time.time()
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
    xgb_model = XGBClassifier().fit(x_train, y_train)
    probs_xg = xgb_model.predict_proba(x_test)[:, 1]
    probs_xg_scol.append(probs_xg)
    # predict
    xgb_y_predict = xgb_model.predict(x_test)
    fxg = f1_score(xgb_y_predict,y_test)
    f1_xg_scol.append(fxg)
    rocauc_xg = roc_auc_score(xgb_y_predict, y_test)
    rocauc_xg_scol.append(rocauc_xg)
    recall_xg = recall_score(xgb_y_predict, y_test)
    recall_xg_scol.append(recall_xg)
    precisions_xg = precision_score(xgb_y_predict, y_test)
    precision_xg_scol.append(precisions_xg)
    accuracys_xg = accuracy_score(xgb_y_predict, y_test)
    accuracy_xg_scol.append(accuracys_xg)
    xg_end = time.time()
    print("===XGB with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[0], i)
    print('XGB F1-Score', fxg*100)
    print('XGB ROCAUC Score:', rocauc_xg*100)
    print('XGB Recall score:', recall_xg*100)
    print('XGB Precision Score:', precisions_xg *100)
    print('XGB Confusion Matrix', confusion_matrix(xgb_y_predict, y_test), "\n")
    print('XGB Classification', classification_report(xgb_y_predict, y_test), "\n")
    print('XGB Accuracy Score', accuracys_nb*100)
    print("Execution Time for XGBoost Classifier Tomelinks: ", xg_end - start4, "seconds")

# Random Forest Classifier
    from sklearn.ensemble import RandomForestClassifier
    start5 = time.time()
    rfc_model = RandomForestClassifier(n_estimators=1000, random_state=0).fit(x_train,y_train)
    probs_rf = rfc_model.predict_proba(x_test)[:, 1]
    probs_rf_scol.append(probs_rf)
    rfc_pred = rfc_model.predict(x_test)
    frfc = f1_score(rfc_pred,y_test)
    f1_rf_scol.append(frfc)
    rocauc_rf = roc_auc_score(y_test, rfc_pred)
    rocauc_rf_scol.append(rocauc_rf)
    recalls_rf = recall_score(rfc_pred, y_test)
    recall_rf_scol.append(recalls_rf)
    precisions_rf = precision_score(rfc_pred, y_test)
    precision_rf_scol.append(precisions_rf)
    accuracys_rf = accuracy_score(rfc_pred, y_test)
    accuracy_rf_scol.append(accuracys_rf)
    rf_end = time.time()
    print("====RandomForest with Tfidf Tomelinks 2010", df1_l, test_sizes[0], i)
    print('RFC F1 score', frfc*100)
    print('RFC ROCAUC Score:', rocauc_rf*100)
    print('RFC Recall score:', recalls_rf*100)
    print('RFC Precision Score:', precisions_rf*100)
    print('RFC Confusion Matrix', confusion_matrix(y_test,rfc_pred), "\n")
    print('RFC Classification', classification_report(y_test,rfc_pred), "\n")
    print('RFC Accuracy Score', accuracys_rf*100)
    print("Execution Time for Random Forest Classifier Tomelinks: ", rf_end - start5, "seconds")

    print("Array of Prob Scores LR-Sam Test-Size", test_sizes[0],":", probs_lr_scol)
    print("Array of F1 Scores LR-Sam Test-Size:", test_sizes[0],":", f1_lr_scol)
    print("Array of ROCAUC Scores LR-Sam:", test_sizes[0],":", rocauc_lr_scol)
    print("Array of Recall Scores LR-Sam:", test_sizes[0],":", recall_lr_scol)
    print("Array of Precision Scores LR-Sam:", test_sizes[0],":", precision_lr_scol)
    print("Array of Accuracy Scores LR-Sam:", test_sizes[0],":", accuracy_lr_scol)

    print("Array of Prob Scores DT-Sam:", test_sizes[0],":", probs_dt_scol)
    print("Array of F1 Scores DT-Sam:", test_sizes[0],":", f1_dt_scol)
    print("Array of ROCAUC Scores DT-Sam:", test_sizes[0],":", rocauc_dt_scol)
    print("Array of Recall Scores DT-Sam:", test_sizes[0],":", recall_dt_scol)
    print("Array of Precision Scores DT-Sam:", test_sizes[0],":", precision_dt_scol)
    print("Array of Accuracy Scores DT-Sam:", test_sizes[0],":", accuracy_dt_scol)

    print("Array of Prob Scores NB-Sam:", test_sizes[0],":", probs_nb_scol)
    print("Array of F1 Scores NB-Sam:", test_sizes[0],":", f1_nb_scol)
    print("Array of ROCAUC Scores NB-Sam:", test_sizes[0],":", rocauc_nb_scol)
    print("Array of Recall Scores NB-Sam:", test_sizes[0],":", recall_nb_scol)
    print("Array of Precision Scores NB-Sam:", test_sizes[0],":", precision_nb_scol)
    print("Array of Accuracy Scores NB-Sam:", test_sizes[0],":", accuracy_nb_scol)

    print("Array of Prob Scores XG-Sam:", test_sizes[0],":", probs_xg_scol)
    print("Array of F1 Scores XG-Sam:",  test_sizes[0],":", f1_xg_scol)
    print("Array of ROCAUC Scores XG-Sam:",  test_sizes[0],":",  rocauc_xg_scol)
    print("Array of Recall Scores XG-Sam:",  test_sizes[0],":",  recall_xg_scol)
    print("Array of Precision Scores XG-Sam:",  test_sizes[0],":", precision_xg_scol)
    print("Array of Accuracy Scores XG-Sam:",  test_sizes[0],":", accuracy_xg_scol)

    print("Array of Prob Scores RF-Sam:",  test_sizes[0],":", probs_rf_scol)
    print("Array of F1 Scores RF-Sam:", test_sizes[0],":",  f1_rf_scol)
    print("Array of ROCAUC Scores RF-Sam:",  test_sizes[0],":", rocauc_rf_scol)
    print("Array of Recall Scores RF-Sam:", test_sizes[0],":",  recall_rf_scol)
    print("Array of Precision Scores RF-Sam:", test_sizes[0],":",  precision_rf_scol)
    print("Array of Accuracy Scores RF-Sam:", test_sizes[0],":",  accuracy_rf_scol)
    
precision_Sam1 = (precision_lr_scol[0] + precision_dt_scol[0]+ precision_rf_scol[0] + precision_nb_scol[0] + precision_xg_scol[0] ) / 5
precision_Sam2 = (precision_lr_scol[1] + precision_dt_scol[1]+ precision_rf_scol[1] + precision_nb_scol[1] + precision_xg_scol[1] ) / 5
precision_Sam3 = (precision_lr_scol[2] + precision_dt_scol[2]+ precision_rf_scol[2] + precision_nb_scol[2] + precision_xg_scol[2] ) / 5
'''
precision_Sam4 = (precision_lr_scol[3] + precision_dt_scol[3]+ precision_rf_scol[3] + precision_nb_scol[3] + precision_xg_scol[3] ) / 5
precision_Sam5 = (precision_lr_scol[4] + precision_dt_scol[4]+ precision_rf_scol[4] + precision_nb_scol[4] + precision_xg_scol[4] ) / 5
precision_Sam6 = (precision_lr_scol[5] + precision_dt_scol[5]+ precision_rf_scol[5] + precision_nb_scol[5] + precision_xg_scol[5] ) / 5
precision_Sam7 = (precision_lr_scol[6] + precision_dt_scol[6]+ precision_rf_scol[6] + precision_nb_scol[6] + precision_xg_scol[6] ) / 5
precision_Sam8 = (precision_lr_scol[7] + precision_dt_scol[7]+ precision_rf_scol[7] + precision_nb_scol[7] + precision_xg_scol[7] ) / 5
precision_Sam9 = (precision_lr_scol[8] + precision_dt_scol[8]+ precision_rf_scol[8] + precision_nb_scol[8] + precision_xg_scol[8] ) / 5
precision_Sam10 = (precision_lr_scol[9] + precision_dt_scol[9]+ precision_rf_scol[9] + precision_nb_scol[9] + precision_xg_scol[9] ) / 5
'''

# 2nd Test Size - 60% 

probs_lr_scol1 = []
f1_lr_scol1 = []
rocauc_lr_scol1 = []
recall_lr_scol1 = []
precision_lr_scol1 = []
accuracy_lr_scol1 = []

probs_dt_scol1 = []
f1_dt_scol1 = []
rocauc_dt_scol1 = []
recall_dt_scol1 = []
precision_dt_scol1 = []
accuracy_dt_scol1 = []

probs_nb_scol1 = []
f1_nb_scol1 = []
rocauc_nb_scol1 = []
recall_nb_scol1 = []
precision_nb_scol1 = []
accuracy_nb_scol1 = []

probs_xg_scol1 = []
f1_xg_scol1 = []
rocauc_xg_scol1 = []
recall_xg_scol1 = []
precision_xg_scol1 = []
accuracy_xg_scol1 = []

probs_rf_scol1 = []
f1_rf_scol1 = []
rocauc_rf_scol1 = []
recall_rf_scol1 = []
precision_rf_scol1 = []
accuracy_rf_scol1 = []

train_values2= np.array([0.080, 0.130, 0.180])
# 0.221, 0.261, 0.300, 0.320, 0.340, 0.360, 0.385
test_sizes = np.array([0.5, 0.6, 0.7])
#train_sizes = round(train_list, 3)
for i1 in train_values2:
    # train_sizes = train_sizes + i
    #random_portion = round(np.random.uniform(0.2, 0.5), 3)
    #print(random_portion)
    x_train, x_test, y_train, y_test = train_test_split(x_tl,y_tl, train_size=i1, test_size=test_sizes[1])

    start1 = time.time()
    log = LogisticRegression(penalty='l2',random_state=0, solver='lbfgs', multi_class='auto', max_iter=500)
    model_lr = log.fit(x_train,y_train)
    probs_lr = model_lr.predict_proba(x_test)[:, 1]
    probs_lr_scol1.append(probs_lr)
    ly_prediction = log.predict(x_test)
    fly = f1_score(ly_prediction,y_test)
    f1_lr_scol1.append(fly)
    rocauc_lr = roc_auc_score(y_test, ly_prediction)
    rocauc_lr_scol1.append(rocauc_lr)
    recalls_lr = recall_score(y_test, ly_prediction)
    recall_lr_scol1.append(recalls_lr)
    precisions_lr = precision_score(y_test, ly_prediction)
    precision_lr_scol1.append(precisions_lr)
    accuracys_lr = accuracy_score(y_test, ly_prediction)
    accuracy_lr_scol1.append(accuracys_lr)
    print("===Logistic Regression with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[1], i1)
    lr_end = time.time()
    print('Logistic F1-score',fly*100)
    print('Logistic ROCAUC score:',rocauc_lr*100)
    print('Logistic Recall score:', recalls_lr*100)
    print('Logistic Precision Score:', precisions_lr*100)
    print('Logistic Confusion Matrix', confusion_matrix(y_test,ly_prediction), "\n")
    print('Logistic Classification', classification_report(y_test,ly_prediction), "\n")
    print('Logistic Accuracy Score', accuracys_lr*100)
    print("Execution Time for Logistic Regression Tomelinks: ", lr_end - start1, "seconds")

    start2 = time.time()
    from sklearn.tree import DecisionTreeClassifier
    DCT = DecisionTreeClassifier()
    model_dt = DCT.fit(x_train, y_train)
    probs_dt = model_dt.predict_proba(x_test)[:, 1]
    probs_dt_scol1.append(probs_dt)
    dct_pred = DCT.predict(x_test)
    fdct = f1_score(dct_pred,y_test)
    f1_dt_scol1.append(fdct)
    rocauc_dt = roc_auc_score(y_test, dct_pred)
    rocauc_dt_scol1.append(rocauc_dt)
    recalls_dt = recall_score(y_test, dct_pred)
    recall_dt_scol1.append(recalls_dt)
    precisions_dt = precision_score(y_test, dct_pred)
    precision_dt_scol1.append(precisions_dt)
    accuracys_dt = accuracy_score(y_test, dct_pred)
    accuracy_dt_scol1.append(accuracys_dt)
    print("===DecisionTreeClassifier with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[1], i1)
    dt_end = time.time()
    print('DCT F1-score',fdct*100)
    print('DCT ROCAUC score:',rocauc_dt*100)
    print('DCT Recall score:', recalls_dt*100)
    print('DCT Precision Score:', precisions_dt*100)
    print('DCT Confusion Matrix', confusion_matrix(y_test, dct_pred), "\n")
    print('DCT Classification', classification_report(y_test, dct_pred), "\n")
    print('DCT Accuracy Score', accuracys_dt*100)
    print("Execution Time for Decision Tree Tomelinks: ", dt_end - start2, "seconds")


    from sklearn.naive_bayes import MultinomialNB
    start3 = time.time()
    Naive = MultinomialNB()
    model_nb = Naive.fit(x_train,y_train)
    probs_nb = model_nb.predict_proba(x_test)[:, 1]
    probs_nb_scol1.append(probs_nb)
    # predict the labels on validation dataset
    ny_pred = Naive.predict(x_test)
    fnb = f1_score(ny_pred,y_test)
    f1_nb_scol1.append(fnb)
    rocauc_nb = roc_auc_score(y_test, ny_pred)
    rocauc_nb_scol1.append(rocauc_nb)
    recalls_nb = recall_score(y_test, ny_pred)
    recall_nb_scol1.append(recalls_nb)
    precisions_nb = precision_score(y_test, ny_pred)
    precision_nb_scol1.append(precisions_nb)
    accuracys_nb = accuracy_score(y_test, ny_pred)
    accuracy_nb_scol1.append(accuracys_nb)
    nb_end = time.time()
    # Use accuracy_score function to get the accuracy
    print("===Naive Bayes with TfidfVectorizer Imabalanced - 2010", df1_l, test_sizes[1], i1)
    print('Naive F1-score',fnb*100)
    print('Naive ROCAUC score:',rocauc_nb*100)
    print('Naive Recall score:', recalls_nb*100)
    print('Naive Precision Score:', precisions_nb*100)
    print('Naive Confusion Matrix', confusion_matrix(y_test, ny_pred), "\n")
    print('Naive Classification', classification_report(y_test, ny_pred), "\n")
    print('Naive Accuracy Score', accuracys_nb*100)
    print("Execution Time for Naive Bayes Tomelinks: ", nb_end - start3, "seconds")

# XGBoost Classifier

    start4 = time.time()
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
    xgb_model = XGBClassifier().fit(x_train, y_train)
    probs_xg = xgb_model.predict_proba(x_test)[:, 1]
    probs_xg_scol1.append(probs_xg)
    # predict
    xgb_y_predict = xgb_model.predict(x_test)
    fxg = f1_score(xgb_y_predict,y_test)
    f1_xg_scol1.append(fxg)
    rocauc_xg = roc_auc_score(xgb_y_predict, y_test)
    rocauc_xg_scol1.append(rocauc_xg)
    recall_xg = recall_score(xgb_y_predict, y_test)
    recall_xg_scol1.append(recall_xg)
    precisions_xg = precision_score(xgb_y_predict, y_test)
    precision_xg_scol1.append(precisions_xg)
    accuracys_xg = accuracy_score(xgb_y_predict, y_test)
    accuracy_xg_scol1.append(accuracys_xg)
    xg_end = time.time()
    print("===XGB with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[1], i1)
    print('XGB F1-Score', fxg*100)
    print('XGB ROCAUC Score:', rocauc_xg*100)
    print('XGB Recall score:', recall_xg*100)
    print('XGB Precision Score:', precisions_xg *100)
    print('XGB Confusion Matrix', confusion_matrix(xgb_y_predict, y_test), "\n")
    print('XGB Classification', classification_report(xgb_y_predict, y_test), "\n")
    print('XGB Accuracy Score', accuracys_nb*100)
    print("Execution Time for XGBoost Classifier Tomelinks: ", xg_end - start4, "seconds")

# Random Forest Classifier
    from sklearn.ensemble import RandomForestClassifier
    start5 = time.time()
    rfc_model = RandomForestClassifier(n_estimators=1000, random_state=0).fit(x_train,y_train)
    probs_rf = rfc_model.predict_proba(x_test)[:, 1]
    probs_rf_scol1.append(probs_rf)
    rfc_pred = rfc_model.predict(x_test)
    frfc = f1_score(rfc_pred,y_test)
    f1_rf_scol1.append(frfc)
    rocauc_rf = roc_auc_score(y_test, rfc_pred)
    rocauc_rf_scol1.append(rocauc_rf)
    recalls_rf = recall_score(rfc_pred, y_test)
    recall_rf_scol1.append(recalls_rf)
    precisions_rf = precision_score(rfc_pred, y_test)
    precision_rf_scol1.append(precisions_rf)
    accuracys_rf = accuracy_score(rfc_pred, y_test)
    accuracy_rf_scol1.append(accuracys_rf)
    rf_end = time.time()
    print("====RandomForest with Tfidf Tomelinks 2010", df1_l, test_sizes[1], i1)
    print('RFC F1 score', frfc*100)
    print('RFC ROCAUC Score:', rocauc_rf*100)
    print('RFC Recall score:', recalls_rf*100)
    print('RFC Precision Score:', precisions_rf*100)
    print('RFC Confusion Matrix', confusion_matrix(y_test,rfc_pred), "\n")
    print('RFC Classification', classification_report(y_test,rfc_pred), "\n")
    print('RFC Accuracy Score', accuracys_rf*100)
    print("Execution Time for Random Forest Classifier Tomelinks: ", rf_end - start5, "seconds")

    print("Array of Prob Scores LR-Sam:",  test_sizes[1],":",  probs_lr_scol1)
    print("Array of F1 Scores LR-Sam:",  test_sizes[1],":",  f1_lr_scol1)
    print("Array of ROCAUC Scores LR-Sam:",  test_sizes[1],":",  rocauc_lr_scol1)
    print("Array of Recall Scores LR-Sam:",  test_sizes[1],":",  recall_lr_scol1)
    print("Array of Precision Scores LR-Sam:",  test_sizes[1],":", precision_lr_scol1)
    print("Array of Accuracy Scores LR-Sam:", test_sizes[1],":", accuracy_lr_scol1)

    print("Array of Prob Scores DT-Sam:", test_sizes[1],":", probs_dt_scol1)
    print("Array of F1 Scores DT-Sam:", test_sizes[1],":", f1_dt_scol1)
    print("Array of ROCAUC Scores DT-Sam:", test_sizes[1],":", rocauc_dt_scol1)
    print("Array of Recall Scores DT-Sam:",test_sizes[1],":", recall_dt_scol1)
    print("Array of Precision Scores DT-Sam:", test_sizes[1],":", precision_dt_scol1)
    print("Array of Accuracy Scores DT-Sam:", test_sizes[1],":", accuracy_dt_scol1)

    print("Array of Prob Scores NB-Sam:", test_sizes[1],":", probs_nb_scol1)
    print("Array of F1 Scores NB-Sam:", test_sizes[1],":", f1_nb_scol1)
    print("Array of ROCAUC Scores NB-Sam:", test_sizes[1],":", rocauc_nb_scol1)
    print("Array of Recall Scores NB-Sam:", test_sizes[1],":", recall_nb_scol1)
    print("Array of Precision Scores NB-Sam:", test_sizes[1],":", precision_nb_scol1)
    print("Array of Accuracy Scores NB-Sam:", test_sizes[1],":", accuracy_nb_scol1)

    print("Array of Prob Scores XG-Sam:", test_sizes[1],":", probs_xg_scol1)
    print("Array of F1 Scores XG-Sam:", test_sizes[1],":", f1_xg_scol1)
    print("Array of ROCAUC Scores XG-Sam:", test_sizes[1],":", rocauc_xg_scol1)
    print("Array of Recall Scores XG-Sam:", test_sizes[1],":", recall_xg_scol1)
    print("Array of Precision Scores XG-Sam:", test_sizes[1],":", precision_xg_scol1)
    print("Array of Accuracy Scores XG-Sam:", test_sizes[1],":", accuracy_xg_scol1)

    print("Array of Prob Scores RF-Sam:", test_sizes[1],":", probs_rf_scol1)
    print("Array of F1 Scores RF-Sam:", test_sizes[1],":", f1_rf_scol1)
    print("Array of ROCAUC Scores RF-Sam:", test_sizes[1],":", rocauc_rf_scol1)
    print("Array of Recall Scores RF-Sam:", test_sizes[1],":", recall_rf_scol1)
    print("Array of Precision Scores RF-Sam:", test_sizes[1],":", precision_rf_scol1)
    print("Array of Accuracy Scores RF-Sam:", test_sizes[1],":", accuracy_rf_scol1)
    
precision_Sam11 = (precision_lr_scol1[0] + precision_dt_scol1[0]+ precision_rf_scol1[0] + precision_nb_scol1[0] + precision_xg_scol1[0] ) / 5
precision_Sam12 = (precision_lr_scol1[1] + precision_dt_scol1[1]+ precision_rf_scol1[1] + precision_nb_scol1[1] + precision_xg_scol1[1] ) / 5
precision_Sam13 = (precision_lr_scol1[2] + precision_dt_scol1[2]+ precision_rf_scol1[2] + precision_nb_scol1[2] + precision_xg_scol1[2] ) / 5
'''
precision_Sam14 = (precision_lr_scol1[3] + precision_dt_scol1[3]+ precision_rf_scol1[3] + precision_nb_scol1[3] + precision_xg_scol1[3] ) / 5
precision_Sam15 = (precision_lr_scol1[4] + precision_dt_scol1[4]+ precision_rf_scol1[4] + precision_nb_scol1[4] + precision_xg_scol1[4] ) / 5
precision_Sam16 = (precision_lr_scol1[5] + precision_dt_scol1[5]+ precision_rf_scol1[5] + precision_nb_scol1[5] + precision_xg_scol1[5] ) / 5
precision_Sam17 = (precision_lr_scol1[6] + precision_dt_scol1[6]+ precision_rf_scol1[6] + precision_nb_scol1[6] + precision_xg_scol1[6] ) / 5
precision_Sam18 = (precision_lr_scol1[7] + precision_dt_scol1[7]+ precision_rf_scol1[7] + precision_nb_scol1[7] + precision_xg_scol1[7] ) / 5
precision_Sam19 = (precision_lr_scol1[8] + precision_dt_scol1[8]+ precision_rf_scol1[8] + precision_nb_scol1[8] + precision_xg_scol1[8] ) / 5
precision_Sam20 = (precision_lr_scol1[9] + precision_dt_scol1[9]+ precision_rf_scol1[9] + precision_nb_scol1[9] + precision_xg_scol1[9] ) / 5
'''

x_tfidf = tfidf_vect.fit_transform(df["lemmatized"])

probs_lr_scol2 = []
f1_lr_scol2 = []
rocauc_lr_scol2 = []
recall_lr_scol2 = []
precision_lr_scol2 = []
accuracy_lr_scol2 = []

probs_dt_scol2 = []
f1_dt_scol2 = []
rocauc_dt_scol2 = []
recall_dt_scol2 = []
precision_dt_scol2 = []
accuracy_dt_scol2 = []

probs_nb_scol2 = []
f1_nb_scol2 = []
rocauc_nb_scol2 = []
recall_nb_scol2 = []
precision_nb_scol2 = []
accuracy_nb_scol2 = []

probs_xg_scol2 = []
f1_xg_scol2 = []
rocauc_xg_scol2 = []
recall_xg_scol2 = []
precision_xg_scol2 = []
accuracy_xg_scol2 = []

probs_rf_scol2 = []
f1_rf_scol2 = []
rocauc_rf_scol2 = []
recall_rf_scol2 = []
precision_rf_scol2 = []
accuracy_rf_scol2 = []

train_values3= np.array([0.056, 0.076, 0.100])
# 0.125, 0.169, 0.195, 0.215, 0.797, 0.800, 0.900
test_sizes = np.array([0.5, 0.6, 0.7])
#train_sizes = round(train_list, 3)
for i2 in train_values3:
    # train_sizes = train_sizes + i
    #random_portion = round(np.random.uniform(0.2, 0.5), 3)
    #print(random_portion)
    x_train, x_test, y_train, y_test = train_test_split(x_tfidf,df["label"], train_size=i2, test_size=test_sizes[2])

    start1 = time.time()
    log = LogisticRegression(penalty='l2',random_state=0, solver='lbfgs', multi_class='auto', max_iter=500)
    model_lr = log.fit(x_train,y_train)
    probs_lr = model_lr.predict_proba(x_test)[:, 1]
    probs_lr_scol2.append(probs_lr)
    ly_prediction = log.predict(x_test)
    fly = f1_score(ly_prediction,y_test)
    f1_lr_scol2.append(fly)
    rocauc_lr = roc_auc_score(y_test, ly_prediction)
    rocauc_lr_scol2.append(rocauc_lr)
    recalls_lr = recall_score(y_test, ly_prediction)
    recall_lr_scol2.append(recalls_lr)
    precisions_lr = precision_score(y_test, ly_prediction)
    precision_lr_scol2.append(precisions_lr)
    accuracys_lr = accuracy_score(y_test, ly_prediction)
    accuracy_lr_scol2.append(accuracys_lr)
    print("===Logistic Regression with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[2], i2)
    lr_end = time.time()
    print('Logistic F1-score',fly*100)
    print('Logistic ROCAUC score:',rocauc_lr*100)
    print('Logistic Recall score:', recalls_lr*100)
    print('Logistic Precision Score:', precisions_lr*100)
    print('Logistic Confusion Matrix', confusion_matrix(y_test,ly_prediction), "\n")
    print('Logistic Classification', classification_report(y_test,ly_prediction), "\n")
    print('Logistic Accuracy Score', accuracys_lr*100)
    print("Execution Time for Logistic Regression Tomelinks: ", lr_end - start1, "seconds")

    start2 = time.time()
    from sklearn.tree import DecisionTreeClassifier
    DCT = DecisionTreeClassifier()
    model_dt = DCT.fit(x_train, y_train)
    probs_dt = model_dt.predict_proba(x_test)[:, 1]
    probs_dt_scol2.append(probs_dt)
    dct_pred = DCT.predict(x_test)
    fdct = f1_score(dct_pred,y_test)
    f1_dt_scol2.append(fdct)
    rocauc_dt = roc_auc_score(y_test, dct_pred)
    rocauc_dt_scol2.append(rocauc_dt)
    recalls_dt = recall_score(y_test, dct_pred)
    recall_dt_scol2.append(recalls_dt)
    precisions_dt = precision_score(y_test, dct_pred)
    precision_dt_scol2.append(precisions_dt)
    accuracys_dt = accuracy_score(y_test, dct_pred)
    accuracy_dt_scol2.append(accuracys_dt)
    print("===DecisionTreeClassifier with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[2], i2)
    dt_end = time.time()
    print('DCT F1-score',fdct*100)
    print('DCT ROCAUC score:',rocauc_dt*100)
    print('DCT Recall score:', recalls_dt*100)
    print('DCT Precision Score:', precisions_dt*100)
    print('DCT Confusion Matrix', confusion_matrix(y_test, dct_pred), "\n")
    print('DCT Classification', classification_report(y_test, dct_pred), "\n")
    print('DCT Accuracy Score', accuracys_dt*100)
    print("Execution Time for Decision Tree Tomelinks: ", dt_end - start2, "seconds")


    from sklearn.naive_bayes import MultinomialNB
    start3 = time.time()
    Naive = MultinomialNB()
    model_nb = Naive.fit(x_train,y_train)
    probs_nb = model_nb.predict_proba(x_test)[:, 1]
    probs_nb_scol2.append(probs_nb)
    # predict the labels on validation dataset
    ny_pred = Naive.predict(x_test)
    fnb = f1_score(ny_pred,y_test)
    f1_nb_scol2.append(fnb)
    rocauc_nb = roc_auc_score(y_test, ny_pred)
    rocauc_nb_scol2.append(rocauc_nb)
    recalls_nb = recall_score(y_test, ny_pred)
    recall_nb_scol2.append(recalls_nb)
    precisions_nb = precision_score(y_test, ny_pred)
    precision_nb_scol2.append(precisions_nb)
    accuracys_nb = accuracy_score(y_test, ny_pred)
    accuracy_nb_scol2.append(accuracys_nb)
    nb_end = time.time()
    # Use accuracy_score function to get the accuracy
    print("===Naive Bayes with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[2], i2)
    print('Naive F1-score',fnb*100)
    print('Naive ROCAUC score:',rocauc_nb*100)
    print('Naive Recall score:', recalls_nb*100)
    print('Naive Precision Score:', precisions_nb*100)
    print('Naive Confusion Matrix', confusion_matrix(y_test, ny_pred), "\n")
    print('Naive Classification', classification_report(y_test, ny_pred), "\n")
    print('Naive Accuracy Score', accuracys_nb*100)
    print("Execution Time for Naive Bayes Tomelinks: ", nb_end - start3, "seconds")

# XGBoost Classifier

    start4 = time.time()
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
    xgb_model = XGBClassifier().fit(x_train, y_train)
    probs_xg = xgb_model.predict_proba(x_test)[:, 1]
    probs_xg_scol2.append(probs_xg)
    # predict
    xgb_y_predict = xgb_model.predict(x_test)
    fxg = f1_score(xgb_y_predict,y_test)
    f1_xg_scol2.append(fxg)
    rocauc_xg = roc_auc_score(xgb_y_predict, y_test)
    rocauc_xg_scol2.append(rocauc_xg)
    recall_xg = recall_score(xgb_y_predict, y_test)
    recall_xg_scol2.append(recall_xg)
    precisions_xg = precision_score(xgb_y_predict, y_test)
    precision_xg_scol2.append(precisions_xg)
    accuracys_xg = accuracy_score(xgb_y_predict, y_test)
    accuracy_xg_scol2.append(accuracys_xg)
    xg_end = time.time()
    print("===XGB with TfidfVectorizer Tomelinks - 2010", df1_l, test_sizes[2], i2)
    print('XGB F1-Score', fxg*100)
    print('XGB ROCAUC Score:', rocauc_xg*100)
    print('XGB Recall score:', recall_xg*100)
    print('XGB Precision Score:', precisions_xg *100)
    print('XGB Confusion Matrix', confusion_matrix(xgb_y_predict, y_test), "\n")
    print('XGB Classification', classification_report(xgb_y_predict, y_test), "\n")
    print('XGB Accuracy Score', accuracys_nb*100)
    print("Execution Time for XGBoost Classifier Tomelinks: ", xg_end - start4, "seconds")

# Random Forest Classifier
    from sklearn.ensemble import RandomForestClassifier
    start5 = time.time()
    rfc_model = RandomForestClassifier(n_estimators=1000, random_state=0).fit(x_train,y_train)
    probs_rf = rfc_model.predict_proba(x_test)[:, 1]
    probs_rf_scol2.append(probs_rf)
    rfc_pred = rfc_model.predict(x_test)
    frfc = f1_score(rfc_pred,y_test)
    f1_rf_scol2.append(frfc)
    rocauc_rf = roc_auc_score(y_test, rfc_pred)
    rocauc_rf_scol2.append(rocauc_rf)
    recalls_rf = recall_score(rfc_pred, y_test)
    recall_rf_scol2.append(recalls_rf)
    precisions_rf = precision_score(rfc_pred, y_test)
    precision_rf_scol2.append(precisions_rf)
    accuracys_rf = accuracy_score(rfc_pred, y_test)
    accuracy_rf_scol2.append(accuracys_rf)
    rf_end = time.time()
    print("====RandomForest with Tfidf Tomelinks 2010", df1_l, test_sizes[2], i2)
    print('RFC F1 score', frfc*100)
    print('RFC ROCAUC Score:', rocauc_rf*100)
    print('RFC Recall score:', recalls_rf*100)
    print('RFC Precision Score:', precisions_rf*100)
    print('RFC Confusion Matrix', confusion_matrix(y_test,rfc_pred), "\n")
    print('RFC Classification', classification_report(y_test,rfc_pred), "\n")
    print('RFC Accuracy Score', accuracys_rf*100)
    print("Execution Time for Random Forest Classifier Tomelinks: ", rf_end - start5, "seconds")

    print("Array of Prob Scores LR-Sam:",  test_sizes[2],":",  probs_lr_scol2)
    print("Array of F1 Scores LR-Sam:",  test_sizes[2],":",  f1_lr_scol2)
    print("Array of ROCAUC Scores LR-Sam:",  test_sizes[2],":",  rocauc_lr_scol2)
    print("Array of Recall Scores LR-Sam:",  test_sizes[2],":",  recall_lr_scol2)
    print("Array of Precision Scores LR-Sam:",  test_sizes[2],":", precision_lr_scol2)
    print("Array of Accuracy Scores LR-Sam:", test_sizes[2],":", accuracy_lr_scol2)

    print("Array of Prob Scores DT-Sam:", test_sizes[2],":", probs_dt_scol2)
    print("Array of F1 Scores DT-Sam:", test_sizes[2],":", f1_dt_scol2)
    print("Array of ROCAUC Scores DT-Sam:", test_sizes[2],":", rocauc_dt_scol2)
    print("Array of Recall Scores DT-Sam:",test_sizes[2],":", recall_dt_scol2)
    print("Array of Precision Scores DT-Sam:", test_sizes[2],":", precision_dt_scol2)
    print("Array of Accuracy Scores DT-Sam:", test_sizes[2],":", accuracy_dt_scol2)

    print("Array of Prob Scores NB-Sam:", test_sizes[2],":", probs_nb_scol2)
    print("Array of F1 Scores NB-Sam:", test_sizes[2],":", f1_nb_scol2)
    print("Array of ROCAUC Scores NB-Sam:", test_sizes[2],":", rocauc_nb_scol2)
    print("Array of Recall Scores NB-Sam:", test_sizes[2],":", recall_nb_scol2)
    print("Array of Precision Scores NB-Sam:", test_sizes[2],":", precision_nb_scol2)
    print("Array of Accuracy Scores NB-Sam:", test_sizes[2],":", accuracy_nb_scol2)

    print("Array of Prob Scores XG-Sam:", test_sizes[2],":", probs_xg_scol2)
    print("Array of F1 Scores XG-Sam:", test_sizes[2],":", f1_xg_scol2)
    print("Array of ROCAUC Scores XG-Sam:", test_sizes[2],":", rocauc_xg_scol2)
    print("Array of Recall Scores XG-Sam:", test_sizes[2],":", recall_xg_scol2)
    print("Array of Precision Scores XG-Sam:", test_sizes[2],":", precision_xg_scol2)
    print("Array of Accuracy Scores XG-Sam:", test_sizes[2],":", accuracy_xg_scol2)

    print("Array of Prob Scores RF-Sam:", test_sizes[2],":", probs_rf_scol2)
    print("Array of F1 Scores RF-Sam:", test_sizes[2],":", f1_rf_scol2)
    print("Array of ROCAUC Scores RF-Sam:", test_sizes[2],":", rocauc_rf_scol2)
    print("Array of Recall Scores RF-Sam:", test_sizes[2],":", recall_rf_scol2)
    print("Array of Precision Scores RF-Sam:", test_sizes[2],":", precision_rf_scol2)
    print("Array of Accuracy Scores RF-Sam:", test_sizes[2],":", accuracy_rf_scol2)
    
precision_Sam21 = (precision_lr_scol2[0] + precision_dt_scol2[0]+ precision_rf_scol2[0] + precision_nb_scol2[0] + precision_xg_scol2[0] ) / 5
precision_Sam22 = (precision_lr_scol2[1] + precision_dt_scol2[1]+ precision_rf_scol2[1] + precision_nb_scol2[1] + precision_xg_scol2[1] ) / 5
precision_Sam23 = (precision_lr_scol2[2] + precision_dt_scol2[2]+ precision_rf_scol2[2] + precision_nb_scol2[2] + precision_xg_scol2[2] ) / 5
'''
precision_Sam24 = (precision_lr_scol2[3] + precision_dt_scol2[3]+ precision_rf_scol2[3] + precision_nb_scol2[3] + precision_xg_scol2[3] ) / 5
precision_Sam25 = (precision_lr_scol2[4] + precision_dt_scol2[4]+ precision_rf_scol2[4] + precision_nb_scol2[4] + precision_xg_scol2[4] ) / 5
precision_Sam26 = (precision_lr_scol2[5] + precision_dt_scol2[5]+ precision_rf_scol2[5] + precision_nb_scol2[5] + precision_xg_scol2[5] ) / 5
precision_Sam27 = (precision_lr_scol2[6] + precision_dt_scol2[6]+ precision_rf_scol2[6] + precision_nb_scol2[6] + precision_xg_scol2[6] ) / 5
precision_Sam28 = (precision_lr_scol2[7] + precision_dt_scol2[7]+ precision_rf_scol2[7] + precision_nb_scol2[7] + precision_xg_scol2[7] ) / 5
precision_Sam29 = (precision_lr_scol2[8] + precision_dt_scol2[8]+ precision_rf_scol2[8] + precision_nb_scol2[8] + precision_xg_scol2[8] ) / 5
precision_Sam30 = (precision_lr_scol2[9] + precision_dt_scol2[9]+ precision_rf_scol2[9] + precision_nb_scol2[9] + precision_xg_scol2[9] ) / 5
'''

plt.figure(figsize=(25, 14))
split1 = [precision_Sam1, precision_Sam2, precision_Sam3]
split2 = [precision_Sam11, precision_Sam12, precision_Sam13]
split3 = [precision_Sam21, precision_Sam22, precision_Sam23]
y_axis = [(split1), (split2), (split3)]
plt.title('Precision: Imbalanced - Randomization 2010')
ticks = ["50%", "60%", "70%"]
plt.yticks(range(0, len(ticks) * 2, 2), ticks)
plt.plot(precision_Sam1, precision_Sam1, label=f'50%: Iteration 1')
plt.plot(precision_Sam2, precision_Sam2, label=f'50%: Iteration 2')
plt.plot(precision_Sam3, precision_Sam3, label=f'50%: Iteration 3')
plt.plot(precision_Sam11, precision_Sam11, label=f'60%: Iteration 1')
plt.plot(precision_Sam12, precision_Sam12, label=f'60%: Iteration 2')
plt.plot(precision_Sam13, precision_Sam13, label=f'60%: Iteration 3')
plt.plot(precision_Sam21, precision_Sam21, label=f'70%: Iteration 1')
plt.plot(precision_Sam22, precision_Sam22, label=f'70%: Iteration 2')
plt.plot(precision_Sam23, precision_Sam23, label=f'70%: Iteration 3')
plt.xlabel('Precision', size=14)
plt.ylabel('Training Size & Testing', size=14)
plt.legend()
plt.show();