---
  title: "Programming Summary"
author: "Jose Dixon"
date: "December 9, 2022"
output:
  word_document: default
pdf_document: default
html_document:
  code_folding: show
---
  
  
```{r WD}
getwd()
```

```{r setup, include=TRUE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error = TRUE)
```


```{r Load Libraries}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(reshape)
library(ggplot2)
library(modelr)
library(tinytex)
options(na.action = na.warn)
```


```{r Testcode}
table <- read.csv("~/Document-Classification/classifier/NIST_Complete_Iterations.csv")
head(table)
# df1 <- data.frame(table)
# df1
```

# ```{r Assignment}
# accuracy = df1[, 12]
# auc = df1[, 11]
# recall = df1[, 10]
# precision = df1[, 9]
# trainingdata = df1[, 8]
# split = df1[, 7]
# trainsplitsize = df1[, 6]
# testsplitsize = df1[, 5]
# classifier = df1[, 4]
# sampling = df1[, 2]
# technique = df1[, 3]
# year = df1[, 1]
# ```

```{r Subset Data}
df <- data.frame(year=table[, 1],
                 sampling=table[, 2],
                 technique=table[, 3],
                 classifier=table[, 4],
                 testsplitsize=table[, 5],
                 trainsplitsize=table[, 6],
                 split=table[, 7],
                 trainingdata=table[, 8],
                 precision=table[, 9],
                 recall=table[, 10],
                 auc=table[, 11],
                 accuracy=table[, 12])

df
```

```{r T-Test Classifier}

naivebayes <- df[df$classifier == 'Naive Bayes', ]
naivebayes
dectree <- df[df$classifier == 'Decision Tree', ]
dectree
randomforest <- df[df$classifier == 'Random Forest', ]
randomforest
logisreg <- df[df$classifier == 'Logistic Regression', ]
logisreg
xgboost <- df[df$classifier == 'XGBoost', ]
xgboost 

tomeklinks <- df[df$technique == 'TomekLinks', ]
tomeklinks
smote <- df[df$technique == 'SMOTE', ]
smote
nearmiss <- df[df$technique == 'NearMiss', ]
nearmiss
ros <- df[df$technique == 'ROS', ]
ros
rus <- df[df$technique == 'RUS', ]
rus

l2010 <- df[df$year == '2010', ]
l2010
l2012 <- df[df$year == '2012', ]
l2012
l2013 <- df[df$year == '2013', ]
l2013
l2014 <- df[df$year == '2014', ]
l2014
l2015 <- df[df$year == '2015', ]
l2015
l2016 <- df[df$year == '2016', ]
l2016
l2017 <- df[df$year == '2017', ]
l2017
l2018 <- df[df$year == '2018', ]
l2018
l2019 <- df[df$year == '2019', ]
l2019


naivebayespre <- c(naivebayes[, 9])
naivebayespre
dectreepre <- c(dectree[, 9])
dectreepre
randomforestpre <- c(randomforest[, 9])
randomforestpre
logisregpre <- c(logisreg[, 9])
logisregpre
xgboostpre <- c(xgboost[, 9])
xgboostpre

naivebayesrec <- c(naivebayes[, 10])
naivebayesrec
dectreerec <- c(dectree[, 10])
dectreerec
randomforestrec <- c(randomforest[, 10])
randomforestrec
logisregrec <- c(logisreg[, 10])
logisregrec
xgboostrec <- c(xgboost[, 10])
xgboostrec
                     
l2010pre <- c(l2010[, 9])
l2010pre
l2012pre <- c(l2012[, 9])
l2012pre 
l2013pre <- c(l2013[, 9])
l2014pre <- c(l2014[, 9])
l2015pre <- c(l2015[, 9])
l2016pre <- c(l2016[, 9])
l2017pre <- c(l2017[, 9])
l2018pre <- c(l2018[, 9])
l2019pre <- c(l2019[, 9])

l2010rec <- c(l2010[, 10])
l2012rec <- c(l2012[, 10])
l2013rec <- c(l2013[, 10])
l2014rec <- c(l2014[, 10])
l2015rec <- c(l2015[, 10])
l2016rec <- c(l2016[, 10])
l2017rec <- c(l2017[, 10])
l2018rec <- c(l2018[, 10])
l2019rec <- c(l2019[, 10])

tomeklinkspre <- c(tomeklinks[, 9])
smotepre <- c(smote[, 9])
nearmisspre <- c(nearmiss[, 9])
ruspre <- c(rus[, 9])
rospre <- c(ros[, 9])

tomeklinksrec <- c(tomeklinks[, 10])
smoterec <- c(smote[, 10])
nearmissrec <- c(nearmiss[, 10])
rusrec <- c(rus[, 10])
rosrec <- c(ros[, 10])

```

```{r T-Test Run}



# as_tibble(df)
# print(df)
# 
# stat.test <- df %>%
#   group_by(classifier) %>%
#   t_test(precision ~ technique) %>%
#   adjust_pvalue(method = "BH") %>%
#   add_significance()
# stat.test


# # Group the data by variables and do a graph for each variable
# graphs <- df %>%
#   group_by(classifier) %>%
#   doo(
#     ~ggboxplot(
#       table =., x = classifier, y = precision,
#       fill = classifier, palette = "npg", legend = "none",
#       ggtheme = theme_pubr()
#       ), 
#     result = "plots"
#   )
# graphs

# # Create the plot
# myplot <- ggboxplot(
#   df, x = "classifier", y = "p-value",
#   fill = "classifier", palette = "npg", legend = "none",
#   ggtheme = theme_pubr(border = TRUE)
#   ) +
#   facet_wrap(~classifier)
# # Add statistical test p-values
# stat.test <- stat.test %>% add_xy_position(x = "classifier")
# myplot + stat_pvalue_manual(stat.test, label = "p.adj.signif")
# 
# df %>%
#   filter(classifier != "Naive Bayes") %>%
#   as_tibble()
# df %>% sample_n(6)
# 


# lpredf <- data.frame(pre2010=l2010pre, pre2012=l2012pre, pre2013=l2013pre)
# print(lpredf)
# 
# # Create the plot
# lpredf_plot <- ggboxplot(
#   lpredf, x = "Precision By Year", y = "P-value",
#   fill = "Precision by Year", palette = "npg", legend = "none",
#   ggtheme = theme_pubr(border = TRUE)
#   ) +
#   facet_wrap(~variables)
# # Add statistical test p-values
# stat.test <- stat.test %>% add_xy_position(x = "P-value")
# lpredf1_plot + stat_pvalue_manual(stat.test, label = "p.adj.signif")



# for(i in 1:length(l2010pre)) {
#   for(j in 1:length(l2012pre)) {
#     matrixi <- l2010pre[[i]]
#     matrixj <- l2012pre[[j]]
#     l2010pre[[i]] <- matrixi
#     l2012pre[[j]] <- matrixj
#     
#     model <- t.test(x=matrixi,y=matrixj)
#     list(p=model$p.value,
#       z=model$statistic)
#   }
# }  

```


```{r Plotting}
dat_ggplot <- data.frame(
  pvalue = c(logisregpre), c(dectreepre), c(naivebayespre), c(xgboostpre), c(randomforestpre),
  sample = c(rep("LogisReg Pre", 1800), rep("DataTree pre", 1800), rep("NaiveBayes pre", 1800), rep("XGBoost Pre", 1800), rep("Random Forest pre", 1800))
)





ggplot(dat_ggplot) +
  aes(x = sample, y = pvalue) +
  geom_boxplot() +
  theme_minimal()

boxplot(pvalue ~ sample,
  data = dat_ggplot
)

t.test(logisregpre, dectreepre)
t.test(logisregpre, naivebayespre)
t.test(logisregpre, xgboostpre)
t.test(logisregpre, randomforestpre)

```


```{r Plotting 1}
dat_ggplot1 <- data.frame(
  pvalue1 = c(l2010pre), c(l2012pre), c(l2013pre),
  sample1 = c(rep("2010 Pre", 3000), rep("2012 pre", 3000), rep("2013 pre", 3000))
)





ggplot(dat_ggplot1) +
  aes(x = sample1, y = pvalue1) +
  geom_boxplot() +
  theme_minimal()

boxplot(pvalue1 ~ sample1,
  data = dat_ggplot1
)

t.test(l2010pre, l2012pre)
t.test(l2010pre, l2013pre)
t.test(l2012pre, l2010pre)
t.test(l2012pre, l2012pre)
t.test(l2013pre, l2010pre)
t.test(l2013pre, l2012pre)

```

```{r Plotting 2}
dat_ggplot2 <- data.frame(
  pvalue2 = c(l2010rec), c(l2012rec), c(l2013rec),
  sample2 = c(rep("2010 Rec", 3000), rep("2012 Rec", 3000), rep("2013 Rec", 3000))
)





ggplot(dat_ggplot2) +
  aes(x = sample2, y = pvalue2) +
  geom_boxplot() +
  theme_minimal()

boxplot(pvalue2 ~ sample2,
  data = dat_ggplot2
)

t.test(l2010rec, l2012rec)
t.test(l2010rec, l2013rec)
t.test(l2012rec, l2010rec)
t.test(l2012rec, l2012rec)
t.test(l2013rec, l2010rec)
t.test(l2013rec, l2012rec)
```

```{r Plotting 3}
dat_ggplot3 <- data.frame(
  pvalue3 = c(tomeklinksrec), c(smoterec), c(nearmissrec), c(rosrec), c(rusrec),
  sample3 = c(rep("Tomeklinks Rec", 3000), rep("SMOTE Rec", 3000), rep("NearMiss Rec", 3000), rep("ROS Rec", 3000), rep("RUS Rec", 3000))
)





ggplot(dat_ggplot3) +
  aes(x = sample3, y = pvalue3) +
  geom_boxplot() +
  theme_minimal()

boxplot(pvalue3 ~ sample3,
  data = dat_ggplot3
)

t.test(tomeklinksrec, smoterec)
t.test(tomeklinksrec, nearmissrec)
t.test(tomeklinksrec, rosrec)
t.test(tomeklinksrec, rusrec)
```

